services:
  app:
    container_name: web3-lab-react-mui-app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
    - type: bind
      source: ./app
      target: /workspaces/web3-lab-react-mui/app
    - type: volume
      source: node_modules
      target: /workspaces/web3-lab-react-mui/app/node_modules
    command: /bin/sh
    ports:
      - 3000:3000
    stdin_open: true
    tty: true

volumes:
  node_modules: